packages:
  - packages/*

catalog:
  '@types/node': ^24.10.4
  dotenv: ^17.2.3
  drizzle-orm: ^0.45.1
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  globals: ^16.5.0
  postgres: ^3.4.7
  prettier: ^3.7.4
  turbo: ^2.7.1
  typescript: ^5.9.3
  typescript-eslint: ^8.50.0
  vitest: ^4.0.16

onlyBuiltDependencies:
  - esbuild
  - msgpackr-extract
