packages:
  - packages/*

catalog:
  '@ianvs/prettier-plugin-sort-imports': ^4.7.0
  '@types/node': ^24.10.4
  discord.js: ^14.25.1
  dotenv: ^17.2.3
  drizzle-orm: ^0.45.1
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  globals: ^16.5.0
  postgres: ^3.4.7
  prettier: ^3.7.4
  turbo: ^2.7.2
  typescript: ^5.9.3
  typescript-eslint: ^8.50.1
  vitest: ^4.0.16

onlyBuiltDependencies:
  - esbuild
  - msgpackr-extract
